"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables d'environnement depuis backend/.env si présent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-qqk_exi84e*j9w5m+bzv&tg$)mk+eif705+e1bgtrs5x=i8e)d',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tierces
    'rest_framework',
    'corsheaders',
    # Apps locales
    'comptes',
    'candidatures',
]

# Identifiant de connexion = email (voir comptes.User).
AUTH_USER_MODEL = 'comptes.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sert les fichiers statiques (admin, DRF) directement depuis Gunicorn en
    # production — pas besoin de les monter dans Nginx. Sans effet en dev.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Dev : SQLite par défaut. Production : définir DB_ENGINE=postgresql + les
# variables DB_* dans .env pour basculer vers PostgreSQL sans changer le code.

if os.getenv('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'acgt_recrutement'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Kinshasa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Cible de `collectstatic` en production (servie par WhiteNoise via Gunicorn).
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compresse les statiques ; pas de manifest (évite l'échec si un
        # template référence un statique absent).
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Fichiers privés (pièces jointes) — stockés hors de la racine web servie.
# Étape 1 : dossier privé local. Bascule MinIO/S3 plus tard via django-storages
# sans toucher au code métier.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR.parent / 'fichiers_prives'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

# CORS : autorise le front Vue (Vite) en développement.
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
).split(',')

# Origines de confiance pour le CSRF (le navigateur envoie l'en-tête Origin du
# front). Indispensable quand le front tourne sur un autre port que Django.
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,'
    'http://localhost:5174,http://127.0.0.1:5174',
).split(',')


# Email (Resend)
# Si RESEND_API_KEY est défini -> envoi réel via l'API HTTP Resend.
# Sinon -> backend console (les emails sont affichés dans le terminal en dev).
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
EMAIL_FROM = os.getenv('EMAIL_FROM', 'notifications@recrutement.acgt.cd')
EMAIL_FROM_NOM = os.getenv('EMAIL_FROM_NOM', 'ACGT Recrutement')
# Adresse de réponse réelle (boîte consultée). Améliore la délivrabilité.
EMAIL_REPLY_TO = os.getenv('EMAIL_REPLY_TO', 'recrutement@acgt.cd')
# Nom public de la plateforme, réutilisé dans les templates d'emails.
SITE_NOM = os.getenv('SITE_NOM', 'Plateforme de recrutement ACGT')

# URL du front Vue, base des liens envoyés par email (vérification, reset).
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')


# --- Sécurité derrière le reverse-proxy Nginx (production HTTPS) ---
# Nginx termine le TLS et transmet X-Forwarded-Proto : Django sait alors que la
# requête d'origine est en HTTPS (redirections, cookies sécurisés corrects).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Réglages activés uniquement hors DEBUG (donc en production).
if not DEBUG:
    # Cookies de session et CSRF transmis uniquement sur HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Redirige tout HTTP résiduel vers HTTPS (en plus de la redirection Nginx).
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    # HSTS : force le navigateur à n'utiliser que HTTPS (1 an).
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
