# Generated by Django 6.0.6 on 2026-06-08 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('cloture', 'Clôturé')], default='brouillon', max_length=20, verbose_name='statut')),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="date d'ouverture")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='date de clôture')),
                ('liste_retenus_publiee', models.BooleanField(default=False, verbose_name='liste des retenus publiée')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'appel à candidature',
                'verbose_name_plural': 'appels à candidature',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('statut', models.CharField(choices=[('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], db_index=True, default='depose', max_length=20, verbose_name='statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='candidatures.appelcandidature', verbose_name='appel à candidature')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], max_length=20, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], max_length=20, verbose_name='nouveau statut')),
                ('motif', models.TextField(blank=True, verbose_name='motif')),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='candidatures.dossier', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'historique de statut',
                'verbose_name_plural': 'historique des statuts',
                'ordering': ['-horodatage'],
            },
        ),
    ]
