# Generated by Django 6.0.6 on 2026-06-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'type de pièce',
                'verbose_name_plural': 'types de pièce',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PieceExigee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_exigees', to='candidatures.appelcandidature', verbose_name='appel à candidature')),
                ('type_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exigences', to='candidatures.typepiece', verbose_name='type de pièce')),
            ],
            options={
                'verbose_name': 'pièce exigée',
                'verbose_name_plural': 'pièces exigées',
                'ordering': ['ordre', 'type_piece__libelle'],
                'constraints': [models.UniqueConstraint(fields=('appel', 'type_piece'), name='unique_piece_exigee_par_appel')],
            },
        ),
    ]
