# Generated by Django 6.0.6 on 2026-06-08 09:17

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0003_typepiece_pieceexigee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='deposant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='déposant'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], db_index=True, default='brouillon', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='ancien_statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], max_length=20, verbose_name='ancien statut'),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='nouveau_statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('depose', 'Déposé'), ('en_examen', 'En examen'), ('retenu', 'Retenu'), ('non_retenu', 'Non retenu'), ('rejete', 'Rejeté')], max_length=20, verbose_name='nouveau statut'),
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=candidatures.models.chemin_piece_jointe, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name="nom d'origine")),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='candidatures.dossier', verbose_name='dossier')),
                ('type_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to='candidatures.typepiece', verbose_name='type de pièce')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['type_piece__ordre', 'cree_le'],
            },
        ),
    ]
