# Generated by Django 6.0.6 on 2026-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0004_dossier_deposant_alter_dossier_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeEligibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('type_eligibilite', models.CharField(choices=[('stage', 'Stage'), ('candidature', 'Ancienne candidature')], default='stage', max_length=20, verbose_name='type')),
                ('annee', models.PositiveIntegerField(blank=True, null=True, verbose_name='année')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence interne')),
                ('texte_recherche', models.CharField(db_index=True, default='', editable=False, max_length=320, verbose_name='texte de recherche')),
                ('est_publie', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'personne éligible',
                'verbose_name_plural': "liste d'éligibilité",
                'ordering': ['nom', 'postnom', 'prenom'],
            },
        ),
    ]
