# Generated by Django 6.0.6 on 2026-06-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0005_listeeligibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='ligne_eligibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='candidatures.listeeligibilite', verbose_name="ligne d'éligibilité"),
        ),
    ]
