# Generated by Django 6.0.6 on 2026-06-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0007_affectationevaluateur_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='texte_recherche',
            field=models.CharField(db_index=True, default='', editable=False, max_length=320, verbose_name='texte de recherche'),
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254, verbose_name='destinataire')),
                ('sujet', models.CharField(max_length=255, verbose_name='sujet')),
                ('template', models.CharField(max_length=100, verbose_name='template')),
                ('contexte', models.JSONField(blank=True, default=dict, verbose_name='contexte')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], db_index=True, default='en_attente', max_length=20, verbose_name='statut')),
                ('tentatives', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='candidatures.dossier', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'email en file',
                'verbose_name_plural': "file d'emails",
                'ordering': ['cree_le'],
            },
        ),
    ]
