# Generated by Django 6.0.6 on 2026-06-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0008_dossier_texte_recherche_emailqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120, unique=True, verbose_name='intitulé')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'poste',
                'verbose_name_plural': 'postes',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='candidatures.poste', verbose_name='poste visé'),
        ),
    ]
