# Generated by Django 6.0.6 on 2026-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0009_poste_dossier_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceexigee',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='plusieurs fichiers autorisés'),
        ),
    ]
