# Generated by Django 6.0.6 on 2026-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0010_pieceexigee_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='candidature_unique',
            field=models.BooleanField(default=False, verbose_name='candidature unique par compte'),
        ),
    ]
