# Generated by Django 6.0.6 on 2026-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0011_appelcandidature_candidature_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeeligibilite',
            name='type_eligibilite',
            field=models.CharField(blank=True, choices=[('stage', 'Stage'), ('candidature', 'Ancienne candidature')], default='stage', max_length=20, verbose_name='type'),
        ),
    ]
