# Generated by Django 6.0.6 on 2026-06-10 14:49

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0012_alter_listeeligibilite_type_eligibilite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationEligibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=20, verbose_name='statut')),
                ('motif', models.TextField(blank=True, verbose_name='motif de la décision')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('texte_recherche', models.CharField(db_index=True, default='', editable=False, max_length=320, verbose_name='texte de recherche')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='reçue le')),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='candidatures.appelcandidature', verbose_name='appel à candidature')),
                ('dossier_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_origine', to='candidatures.dossier', verbose_name='dossier créé')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': "réclamation d'éligibilité",
                'verbose_name_plural': "réclamations d'éligibilité",
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accuse', 'Accusé de réception'), ('cv', 'CV'), ('identite', "Pièce d'identité"), ('diplome', 'Diplôme')], max_length=20, verbose_name='type')),
                ('fichier', models.FileField(upload_to=candidatures.models.chemin_doc_reclamation, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name="nom d'origine")),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidatures.reclamationeligibilite', verbose_name='réclamation')),
            ],
            options={
                'verbose_name': 'document de réclamation',
                'verbose_name_plural': 'documents de réclamation',
                'ordering': ['type', 'cree_le'],
            },
        ),
    ]
