# Generated by Django 6.0.6 on 2026-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0014_listeeligibilite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='code du dossier'),
        ),
    ]
