# Generated by Django 6.0.6 on 2026-06-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0015_dossier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamationeligibilite',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='candidatures.poste', verbose_name='poste souhaité'),
        ),
    ]
