# Generated by Django 6.0.6 on 2026-06-16 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0018_dossier_affecte_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('portee', models.CharField(choices=[('reclamation', 'Réclamation'), ('dossier', 'Dossier'), ('les_deux', 'Les deux')], default='reclamation', help_text="À quel flux ce critère s'applique (l'accusé : réclamation).", max_length=20, verbose_name='portée')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'critère de validation',
                'verbose_name_plural': 'critères de validation',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ControleCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_snapshot', models.CharField(max_length=255, verbose_name='libellé (copie)')),
                ('rempli', models.BooleanField(default=False, verbose_name='rempli')),
                ('le', models.DateTimeField(auto_now=True, verbose_name='le')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='contrôlé par')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='candidatures.reclamationeligibilite', verbose_name='réclamation')),
                ('critere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='candidatures.criterevalidation', verbose_name='critère')),
            ],
            options={
                'verbose_name': 'contrôle de critère',
                'verbose_name_plural': 'contrôles de critères',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('reclamation', 'critere'), name='unique_controle_reclamation_critere')],
            },
        ),
    ]
