# Generated by Django 6.0.6 on 2026-06-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0019_criterevalidation_controlecritere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('email', models.EmailField(max_length=254, verbose_name='email de contact')),
                ('message', models.TextField(verbose_name='message')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité')], db_index=True, default='en_attente', max_length=20, verbose_name='statut')),
                ('reponse', models.TextField(blank=True, verbose_name='réponse / note interne')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours', to='candidatures.dossier', verbose_name='dossier lié')),
                ('reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours', to='candidatures.reclamationeligibilite', verbose_name='réclamation liée')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_traites', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'recours',
                'verbose_name_plural': 'recours',
                'ordering': ['-cree_le'],
            },
        ),
    ]
