# Generated by Django 6.0.6 on 2026-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0020_recours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='message_retenus',
            field=models.TextField(blank=True, verbose_name='message public (page des retenus)'),
        ),
    ]
