# Generated by Django 6.0.6 on 2026-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0021_appelcandidature_message_retenus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='date_limite_recours',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date limite des recours'),
        ),
    ]
