# Generated by Django 6.0.6 on 2026-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0022_appelcandidature_date_limite_recours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recours',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('traite', 'Traité')], db_index=True, default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
