# Generated by Django 6.0.6 on 2026-06-22 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0023_alter_recours_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recours',
            name='affecte_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_affectes', to=settings.AUTH_USER_MODEL, verbose_name='affecté à'),
        ),
    ]
