# Generated by Django 6.0.6 on 2026-06-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0024_recours_affecte_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='liste_definitive_publiee',
            field=models.BooleanField(default=False, verbose_name='liste définitive publiée'),
        ),
        migrations.AddField(
            model_name='appelcandidature',
            name='message_retenus_definitif',
            field=models.TextField(blank=True, verbose_name='message public (liste définitive)'),
        ),
        migrations.CreateModel(
            name='RetenuDefinitif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='code')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('poste_libelle', models.CharField(blank=True, max_length=120, verbose_name='domaine')),
                ('origine', models.CharField(choices=[('liste', 'Retenu (liste provisoire)'), ('recours', 'Validé après recours')], default='liste', max_length=10, verbose_name='origine')),
                ('texte_recherche', models.CharField(db_index=True, default='', editable=False, max_length=320, verbose_name='texte de recherche')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenus_definitifs', to='candidatures.appelcandidature', verbose_name='appel à candidature')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_definitives', to='candidatures.dossier', verbose_name='dossier')),
                ('recours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_definitives', to='candidatures.recours', verbose_name='recours')),
            ],
            options={
                'verbose_name': 'retenu (liste définitive)',
                'verbose_name_plural': 'retenus (liste définitive)',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('appel', 'code'), name='unique_code_definitif_par_appel')],
            },
        ),
    ]
