# Generated by Django 6.0.6 on 2026-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0025_appelcandidature_liste_definitive_publiee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='instructions_examen',
            field=models.TextField(blank=True, verbose_name='instructions du test (liste définitive)'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_choisie_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ville choisie le'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_examen',
            field=models.CharField(choices=[('kinshasa', 'Kinshasa'), ('lubumbashi', 'Lubumbashi'), ('mbuji_mayi', 'Mbuji-Mayi')], default='kinshasa', max_length=20, verbose_name='ville du test'),
        ),
    ]
