# Generated by Django 6.0.6 on 2026-06-23 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0026_appelcandidature_instructions_examen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_demandee',
            field=models.CharField(blank=True, choices=[('kinshasa', 'Kinshasa'), ('lubumbashi', 'Lubumbashi'), ('mbuji_mayi', 'Mbuji-Mayi')], max_length=20, verbose_name='ville demandée'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_demandee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='demande reçue le'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villes_examen_traitees', to=settings.AUTH_USER_MODEL, verbose_name='ville traitée par'),
        ),
        migrations.AlterField(
            model_name='retenudefinitif',
            name='ville_choisie_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ville confirmée le'),
        ),
    ]
