# Generated by Django 6.0.6 on 2026-06-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0027_retenudefinitif_ville_demandee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='appel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_queue', to='candidatures.appelcandidature', verbose_name='appel à candidature'),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='categorie',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='catégorie'),
        ),
    ]
