# Generated by Django 6.0.6 on 2026-06-24 17:34

from django.db import migrations, models
from django.db.models import Q


def backfill_statut(apps, schema_editor):
    """Déduit le statut des demandes existantes (additif : ne remplit qu'un
    champ neuf, ne modifie aucune autre donnée). Validée si la ville a été
    confirmée ; rejetée si traitée sans confirmation ; en attente si une ville
    est encore demandée et non traitée."""
    RetenuDefinitif = apps.get_model('candidatures', 'RetenuDefinitif')
    RetenuDefinitif.objects.filter(ville_choisie_le__isnull=False).update(ville_demande_statut='validee')
    RetenuDefinitif.objects.filter(
        ville_traite_par__isnull=False, ville_choisie_le__isnull=True
    ).update(ville_demande_statut='rejetee')
    (RetenuDefinitif.objects
     .exclude(ville_demandee='').filter(ville_demande_statut='')
     .update(ville_demande_statut='en_attente'))


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0028_emailqueue_appel_emailqueue_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenudefinitif',
            name='ville_demande_statut',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], db_index=True, max_length=12, verbose_name='statut de la demande de ville'),
        ),
        migrations.RunPython(backfill_statut, migrations.RunPython.noop),
    ]
