# Generated by Django 6.0.6 on 2026-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0029_retenudefinitif_ville_demande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenudefinitif',
            name='salle',
            field=models.CharField(blank=True, db_index=True, max_length=4, verbose_name='salle'),
        ),
    ]
