# Generated by Django 6.0.6 on 2026-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0030_retenudefinitif_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='afficher_salle_public',
            field=models.BooleanField(default=False, verbose_name='afficher la salle au public'),
        ),
    ]
