# Generated by Django 6.0.6 on 2026-06-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0031_appelcandidature_afficher_salle_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recours',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours', to='candidatures.poste', verbose_name='domaine (correction)'),
        ),
    ]
