# Generated by Django 6.0.6 on 2026-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0032_recours_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retenudefinitif',
            name='origine',
            field=models.CharField(choices=[('liste', 'Retenu (liste provisoire)'), ('recours', 'Validé après recours'), ('supplement', 'Ajout supplémentaire')], default='liste', max_length=10, verbose_name='origine'),
        ),
    ]
