# Generated by Django 6.0.6 on 2026-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0033_alter_retenudefinitif_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='afficher_supplements_definitif',
            field=models.BooleanField(default=True, verbose_name='afficher les ajouts supplémentaires sur la liste définitive'),
        ),
    ]
