# Generated by Django 6.0.6 on 2026-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0034_appelcandidature_afficher_supplements_definitif'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='liste_interview_publiee',
            field=models.BooleanField(default=False, verbose_name='liste des admis à l’interview publiée'),
        ),
        migrations.AddField(
            model_name='appelcandidature',
            name='message_interview',
            field=models.TextField(blank=True, verbose_name='communiqué (admis à l’interview)'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='admis_interview',
            field=models.BooleanField(db_index=True, default=False, verbose_name='admis à l’interview'),
        ),
    ]
