# Generated by Django 6.0.6 on 2026-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0035_appelcandidature_liste_interview_publiee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenudefinitif',
            name='interview_ordre',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordre (interview)'),
        ),
    ]
