# Generated by Django 6.0.6 on 2026-07-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0036_retenudefinitif_interview_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenudefinitif',
            name='interview_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de l’interview'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='interview_heure',
            field=models.CharField(blank=True, max_length=40, verbose_name='heure d’arrivée'),
        ),
    ]
