# Generated by Django 6.0.6 on 2026-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0037_retenudefinitif_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcandidature',
            name='liste_finale_publiee',
            field=models.BooleanField(default=False, verbose_name='liste finale des retenus publiée'),
        ),
        migrations.AddField(
            model_name='appelcandidature',
            name='message_final',
            field=models.TextField(blank=True, verbose_name='communiqué (retenus finaux)'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='final_ordre',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordre (liste finale)'),
        ),
        migrations.AddField(
            model_name='retenudefinitif',
            name='retenu_final',
            field=models.BooleanField(db_index=True, default=False, verbose_name='retenu final'),
        ),
    ]
